-- Easy Nihongo 학습 기록 스키마
-- Supabase Dashboard > SQL Editor에서 전체를 한 번 실행하세요.

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  birth_date date,
  daily_word_goal integer not null default 10 check (daily_word_goal in (5, 10, 20)),
  streak integer not null default 0 check (streak >= 0),
  last_study_date date,
  speaking_sentence_count integer not null default 0 check (speaking_sentence_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists full_name text;
alter table public.profiles add column if not exists birth_date date;
create unique index if not exists profiles_person_identity_idx
  on public.profiles ((lower(regexp_replace(full_name, '[[:space:]]', '', 'g'))), birth_date)
  where full_name is not null and birth_date is not null;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare
  signup_name text := nullif(trim(new.raw_user_meta_data ->> 'full_name'), '');
  signup_birth_date date := nullif(new.raw_user_meta_data ->> 'birth_date', '')::date;
begin
  if signup_name is null or signup_birth_date is null then
    raise exception 'full_name and birth_date are required';
  end if;

  insert into public.profiles (user_id, full_name, birth_date, daily_word_goal)
  values (
    new.id,
    signup_name,
    signup_birth_date,
    coalesce(nullif(new.raw_user_meta_data ->> 'daily_word_goal', '')::integer, 10)
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'on_auth_user_created') then
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute procedure public.handle_new_user();
  end if;
end $$;

create table if not exists public.chapter_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  chapter_id text not null,
  current_step integer not null default 0 check (current_step >= 0),
  completed boolean not null default false,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, chapter_id)
);

create table if not exists public.word_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  word_id text not null,
  status text not null default 'learning' check (status in ('learning', 'hard', 'known')),
  correct_count integer not null default 0 check (correct_count >= 0),
  wrong_count integer not null default 0 check (wrong_count >= 0),
  last_reviewed_at timestamptz,
  next_review_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, word_id)
);

create table if not exists public.review_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  review_id text not null,
  repetitions integer not null default 0 check (repetitions >= 0),
  ease_factor numeric(3,2) not null default 2.50 check (ease_factor >= 1.30),
  interval_days integer not null default 1 check (interval_days >= 1),
  next_review_at timestamptz not null default now(),
  last_result text check (last_result in ('again', 'hard', 'good')),
  updated_at timestamptz not null default now(),
  primary key (user_id, review_id)
);

create table if not exists public.study_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  study_date date not null default current_date,
  words_reviewed integer not null default 0 check (words_reviewed >= 0),
  sentences_spoken integer not null default 0 check (sentences_spoken >= 0),
  chapters_completed integer not null default 0 check (chapters_completed >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists chapter_progress_user_id_idx on public.chapter_progress(user_id);
create index if not exists word_progress_user_id_idx on public.word_progress(user_id);
create index if not exists word_progress_next_review_idx on public.word_progress(user_id, next_review_at);
create index if not exists review_progress_user_id_idx on public.review_progress(user_id);
create index if not exists review_progress_next_review_idx on public.review_progress(user_id, next_review_at);
create index if not exists study_sessions_user_id_idx on public.study_sessions(user_id);

alter table public.profiles enable row level security;
alter table public.chapter_progress enable row level security;
alter table public.word_progress enable row level security;
alter table public.review_progress enable row level security;
alter table public.study_sessions enable row level security;

revoke all on table public.profiles, public.chapter_progress, public.word_progress, public.review_progress, public.study_sessions from anon;
grant select, insert, update, delete on table public.profiles, public.chapter_progress, public.word_progress, public.review_progress, public.study_sessions to authenticated;
grant usage, select on sequence public.study_sessions_id_seq to authenticated;

do $$
declare table_name text;
begin
  foreach table_name in array array['profiles','chapter_progress','word_progress','review_progress','study_sessions'] loop
    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = table_name and policyname = 'Users select own rows') then
      execute format('create policy "Users select own rows" on public.%I for select to authenticated using ((select auth.uid()) = user_id)', table_name);
    end if;
    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = table_name and policyname = 'Users insert own rows') then
      execute format('create policy "Users insert own rows" on public.%I for insert to authenticated with check ((select auth.uid()) = user_id)', table_name);
    end if;
    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = table_name and policyname = 'Users update own rows') then
      execute format('create policy "Users update own rows" on public.%I for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)', table_name);
    end if;
    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = table_name and policyname = 'Users delete own rows') then
      execute format('create policy "Users delete own rows" on public.%I for delete to authenticated using ((select auth.uid()) = user_id)', table_name);
    end if;
  end loop;
end $$;
